import { useState, useContext, useEffect } from "react";
import { ThemeContext } from "../../context/ThemeContext";
import { getHistory, deleteHistory, getCurrentUser } from "../../services/api";

export default function AdminCallRecords() {
  const { theme } = useContext(ThemeContext);
  const isDark = theme === "dark" || (theme === "system" && window.matchMedia("(prefers-color-scheme: dark)").matches);
  const [searchTerm, setSearchTerm] = useState("");
  const [filterSentiment, setFilterSentiment] = useState("All");
  const [filterStatus, setFilterStatus] = useState("All");
  const [expandedRecord, setExpandedRecord] = useState(null);
  const [selectedCallRecord, setSelectedCallRecord] = useState(null);
  const [showDetailsModal, setShowDetailsModal] = useState(false);
  const [successMessage, setSuccessMessage] = useState("");
  const [showAudioPlayer, setShowAudioPlayer] = useState(false);
  const [callRecords, setCallRecords] = useState([]);
  const [loading, setLoading] = useState(true);
  const [adminUser, setAdminUser] = useState(null);

  useEffect(() => {
    const fetchAdmin = async () => {
      try {
        const response = await getCurrentUser();
        setAdminUser(response.user);
      } catch (err) {}
    };
    fetchAdmin();
  }, []);

  useEffect(() => {
    const fetchRecords = async () => {
      try {
        setLoading(true);
        const response = await getHistory(1, 100);
        const transformed = response.history.map((item) => ({
          id: item._id,
          callId: item.call_id || item._id,
          user: item.user_email || adminUser?.email || "Unknown",
          date: new Date(item.timestamp).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }),
          time: new Date(item.timestamp).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" }),
          timestamp: new Date(item.timestamp).toLocaleString(),
          duration: "N/A",
          sentiment: item.text?.sentiment || "N/A",
          sarcasm: item.results?.final_sarcasm_score > 0.5 ? "Yes" : "No",
          language: item.detected_language || "Unknown",
          translationLanguage: item.target_language || "English",
          status: "Completed",
          fileName: item._id + ".wav",
          transcript: item.transcript || "",
        }));
        setCallRecords(transformed);
      } catch (err) {
        console.error("Failed to fetch call records:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchRecords();
  }, [adminUser]);

  const handleClearFilters = () => {
    setSearchTerm("");
    setFilterSentiment("All");
    setFilterStatus("All");
  };

  const allCallRecords = callRecords;

  const showSuccess = (message) => {
    setSuccessMessage(message);
    setTimeout(() => setSuccessMessage(""), 3000);
  };

  const handleDownloadAudio = (record) => {
    const element = document.createElement("a");
    element.setAttribute("href", `data:audio/mpeg;base64,SUQzBAAAAAAAI1NUVElUMQAAABQAAADjTWFzbyBGdWxsICh2MC45LjAgMjAxNQ==`);
    element.setAttribute("download", record.fileName);
    element.style.display = "none";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    showSuccess(`Audio "${record.fileName}" downloaded successfully`);
  };

  const handleDownloadReport = (record) => {
    const reportContent = `MUSE CALL ANALYSIS REPORT\n========================\n\nCall ID: ${record.id}\nUser: ${record.user}\nDate: ${record.date}\nTime: ${record.time}\nDuration: ${record.duration}\n\nLANGUAGE & SENTIMENT\n--------------------\nLanguage: ${record.language}\nSentiment: ${record.sentiment}\nSarcasm Detected: ${record.sarcasm}\n\nPROCESSING STATUS\n-----------------\nStatus: ${record.status}\n\nNOTES\nThis is an automated analysis report generated by MUSE - Multimodal Sentiment & Sarcasm Intelligence System.`;
    const element = document.createElement("a");
    element.setAttribute("href", `data:text/plain;charset=utf-8,${encodeURIComponent(reportContent)}`);
    element.setAttribute("download", `MUSE_report_${record.id}.txt`);
    element.style.display = "none";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    showSuccess(`Report for ${record.id} downloaded successfully`);
  };

  const handleDeleteRecord = async (recordId) => {
    try {
      await deleteHistory(recordId);
      setCallRecords(callRecords.filter(r => r.id !== recordId));
      setExpandedRecord(null);
      showSuccess(`Call record deleted successfully`);
    } catch (err) {
      console.error("Failed to delete record:", err);
      showSuccess("Failed to delete record");
    }
  };

  const handleExportAll = () => {
    if (allCallRecords.length === 0) { showSuccess("No records to export"); return; }
    const headers = ["Call ID", "User", "Timestamp", "Duration", "Sentiment", "Sarcasm", "Audio Language", "Translation Language", "Status", "Transcript"];
    const rows = allCallRecords.map(record => [record.callId || record.id, record.user, record.timestamp, record.duration, record.sentiment, record.sarcasm, record.language, record.translationLanguage || "", record.status, record.transcript || ""]);
    const csvContent = [headers.join(","), ...rows.map(row => row.map(cell => `"${cell}"`).join(","))].join("\n");
    const element = document.createElement("a");
    element.setAttribute("href", `data:text/csv;charset=utf-8,${encodeURIComponent(csvContent)}`);
    element.setAttribute("download", `MUSE_call_records_${new Date().toISOString().split('T')[0]}.csv`);
    element.style.display = "none";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    showSuccess(`Exported ${allCallRecords.length} call records successfully`);
  };

  const getSentimentColor = (sentiment) => {
    switch (sentiment) {
      case "Positive": return "bg-green-500/20 border-green-400 text-green-700";
      case "Negative": return "bg-red-500/20 border-red-400 text-red-700";
      case "Neutral": return "bg-yellow-500/20 border-yellow-400 text-yellow-700";
      default: return "bg-gray-100 border-gray-200 text-gray-900";
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "Completed": return "bg-green-500/20 border-green-400 text-green-700";
      case "Pending": return "bg-blue-500/20 border-blue-400 text-blue-700";
      case "Failed": return "bg-red-500/20 border-red-400 text-red-700";
      default: return "bg-gray-100 border-gray-200 text-gray-900";
    }
  };

  const filteredRecords = allCallRecords.filter((record) => {
    const matchesSearch = record.id.toLowerCase().includes(searchTerm.toLowerCase()) || (record.user && record.user.toLowerCase().includes(searchTerm.toLowerCase())) || (record.callId && record.callId.toLowerCase().includes(searchTerm.toLowerCase()));
    const matchesSentiment = filterSentiment === "All" || record.sentiment === filterSentiment;
    const matchesStatus = filterStatus === "All" || record.status === filterStatus;
    return matchesSearch && matchesSentiment && matchesStatus;
  });

  const totalRecords = allCallRecords.length;
  const completedRecords = allCallRecords.filter((r) => r.status === "Completed").length;

  return (
    <div>
      {loading && (
        <div className="flex items-center justify-center py-12">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-violet-600"></div>
          <p className="ml-4 text-gray-600">Loading call records...</p>
        </div>
      )}

      <div className="flex items-center justify-between mb-8">
        <h1 className="text-3xl font-bold text-gray-900">Call Records</h1>
        <button onClick={handleExportAll} className="px-6 py-2 bg-violet-500/30 border border-violet-400 text-violet-700 rounded-lg hover:bg-violet-500/40 transition font-semibold">Export All</button>
      </div>

      {/* Statistics */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
        <div className="rounded-xl p-6 border border-gray-200 shadow-sm">
          <p className="text-gray-600 text-sm">Total Records</p>
          <h2 className="text-3xl font-bold text-violet-700">{totalRecords}</h2>
        </div>
        <div className="rounded-xl p-6 border border-gray-200 shadow-sm">
          <p className="text-gray-600 text-sm">Completed</p>
          <h2 className="text-3xl font-bold text-green-700">{completedRecords}</h2>
        </div>
        <div className="rounded-xl p-6 border border-gray-200 shadow-sm">
          <p className="text-gray-600 text-sm">Total Duration</p>
          <h2 className="text-3xl font-bold text-purple-700">N/A</h2>
        </div>
        <div className="rounded-xl p-6 border border-gray-200 shadow-sm">
          <p className="text-gray-600 text-sm">Avg Call Duration</p>
          <h2 className="text-3xl font-bold text-orange-700">N/A</h2>
        </div>
      </div>

      {/* Filters */}
      <div className="rounded-xl p-6 border border-gray-200 shadow-sm mb-8">
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-lg font-semibold text-gray-900">Filters</h3>
          <button onClick={handleClearFilters} className="px-4 py-2 bg-gray-200 text-gray-800 rounded-lg hover:bg-gray-300 transition font-medium text-sm">Clear Filters</button>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div>
            <label className="text-gray-600 text-sm block mb-2">Search</label>
            <input type="text" placeholder="Search by ID, user, or file..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="w-full px-4 py-2 rounded-lg bg-white border border-gray-300 text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-violet-500" />
          </div>
          <div>
            <label className="text-gray-600 text-sm block mb-2">Sentiment</label>
            <select value={filterSentiment} onChange={(e) => setFilterSentiment(e.target.value)} className="w-full px-4 py-2 rounded-lg bg-white border border-gray-300 text-gray-900 focus:outline-none focus:ring-2 focus:ring-violet-500">
              <option value="All">All</option>
              <option value="Positive">Positive</option>
              <option value="Neutral">Neutral</option>
              <option value="Negative">Negative</option>
            </select>
          </div>
          <div>
            <label className="text-gray-600 text-sm block mb-2">Status</label>
            <select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)} className="w-full px-4 py-2 rounded-lg bg-white border border-gray-300 text-gray-900 focus:outline-none focus:ring-2 focus:ring-violet-500">
              <option value="All">All</option>
              <option value="Completed">Completed</option>
              <option value="Pending">Pending</option>
              <option value="Failed">Failed</option>
            </select>
          </div>
          <div>
            <label className="text-gray-600 text-sm block mb-2">Filter by Date</label>
            <input type="date" className="w-full px-4 py-2 rounded-lg bg-white text-gray-800 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-violet-500" />
          </div>
        </div>
      </div>

      {/* Table */}
      <div className="rounded-xl border border-gray-200 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className={`border-b ${isDark ? "bg-slate-800 text-gray-100 border-slate-700" : "border-gray-200 bg-gray-50 text-gray-900"}`}>
                <th className={`text-left px-6 py-4 font-bold ${isDark ? "text-gray-100" : "text-gray-900"}`}>Call ID</th>
                <th className={`text-left px-6 py-4 font-bold ${isDark ? "text-gray-100" : "text-gray-900"}`}>User</th>
                <th className={`text-left px-6 py-4 font-bold ${isDark ? "text-gray-100" : "text-gray-900"}`}>Date & Time</th>
                <th className={`text-left px-6 py-4 font-bold ${isDark ? "text-gray-100" : "text-gray-900"}`}>Duration</th>
                <th className={`text-left px-6 py-4 font-bold ${isDark ? "text-gray-100" : "text-gray-900"}`}>Sentiment</th>
                <th className={`text-left px-6 py-4 font-bold ${isDark ? "text-gray-100" : "text-gray-900"}`}>Status</th>
                <th className={`text-left px-6 py-4 font-bold ${isDark ? "text-gray-100" : "text-gray-900"}`}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredRecords.map((record) => (
                <>
                  <tr key={record.id} className={`border-b transition ${isDark ? "border-slate-700 hover:bg-slate-800 text-gray-100" : "border-gray-100 hover:bg-gray-50 text-gray-800"}`}>
                    <td className={`px-6 py-4 font-semibold font-mono cursor-pointer hover:underline ${isDark ? "text-cyan-400" : "text-violet-700"}`} onClick={() => setShowAudioPlayer(record)}>{record.callId || record.id}</td>
                    <td className={`px-6 py-4 ${isDark ? "text-gray-200" : "text-gray-900"}`}>{record.user}</td>
                    <td className={`px-6 py-4 ${isDark ? "text-gray-300" : "text-gray-700"}`}>{record.timestamp}</td>
                    <td className={`px-6 py-4 font-medium ${isDark ? "text-gray-200" : "text-gray-900"}`}>{record.duration}</td>
                    <td className="px-6 py-4">
                      <span className={`inline-block px-3 py-1 rounded-full text-sm font-medium border ${getSentimentColor(record.sentiment)}`}>{record.sentiment}</span>
                    </td>
                    <td className="px-6 py-4">
                      <span className={`inline-block px-3 py-1 rounded-full text-sm font-medium border ${getStatusColor(record.status)}`}>{record.status}</span>
                    </td>
                    <td className="px-6 py-4">
                      <button onClick={() => setExpandedRecord(expandedRecord === record.id ? null : record.id)} className="text-violet-700 hover:text-violet-500 font-medium text-sm transition">
                        {expandedRecord === record.id ? "Hide" : "View"}
                      </button>
                    </td>
                  </tr>

                  {expandedRecord === record.id && (
                    <tr className={`border-b ${isDark ? "bg-slate-800 text-gray-100 border-slate-700" : "bg-gray-50 text-gray-800 border-gray-100"}`}>
                      <td colSpan="7" className="px-6 py-6">
                        <div className="flex justify-center">
                          <div className="text-center">
                            <h4 className="text-lg font-semibold text-gray-900 mb-4">Actions</h4>
                            <div className="space-y-2 flex flex-col max-w-xs mx-auto">
                              <button onClick={() => { setSelectedCallRecord(record); setShowDetailsModal(true); }} className="px-4 py-2 bg-purple-500/30 border border-purple-400 text-purple-700 rounded-lg hover:bg-purple-500/40 transition text-sm font-medium">View Details</button>
                              <button onClick={() => handleDownloadAudio(record)} className="px-4 py-2 bg-violet-500/30 border border-violet-400 text-violet-700 rounded-lg hover:bg-violet-500/40 transition text-sm font-medium">Download Audio</button>
                              <button onClick={() => handleDownloadReport(record)} className="px-4 py-2 bg-purple-500/30 border border-purple-400 text-purple-700 rounded-lg hover:bg-purple-500/40 transition text-sm font-medium">Download Report</button>
                              <button onClick={() => handleDeleteRecord(record.id)} className="px-4 py-2 bg-red-500/30 border border-red-400 text-red-700 rounded-lg hover:bg-red-500/40 transition text-sm font-medium">Delete Record</button>
                            </div>
                          </div>
                        </div>
                      </td>
                    </tr>
                  )}
                </>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {filteredRecords.length === 0 && !loading && (
        <div className="rounded-xl p-12 text-center border border-gray-200 shadow-sm">
          <p className="text-gray-700 text-lg">No call records found matching your filters</p>
        </div>
      )}

      {/* Call Details Modal */}
      {showDetailsModal && selectedCallRecord && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50">
          <div className="rounded-xl p-8 border border-gray-200 shadow-sm w-full max-w-lg bg-white">
            <h3 className="text-2xl font-semibold text-gray-900 mb-6">Call Details</h3>
            <div className="space-y-4 mb-6">
              <div className="flex justify-between"><span className="text-gray-700 font-medium">Call ID:</span><span className="text-gray-900 font-mono">{selectedCallRecord.callId}</span></div>
              <div className="flex justify-between"><span className="text-gray-700 font-medium">User:</span><span className="text-gray-900">{selectedCallRecord.user}</span></div>
              <div className="flex justify-between"><span className="text-gray-700 font-medium">Date:</span><span className="text-gray-900">{selectedCallRecord.date}</span></div>
              <div className="flex justify-between"><span className="text-gray-700 font-medium">Time:</span><span className="text-gray-900">{selectedCallRecord.time}</span></div>
              <div className="flex justify-between"><span className="text-gray-700 font-medium">Duration:</span><span className="text-gray-900">{selectedCallRecord.duration}</span></div>
              <div className="flex justify-between"><span className="text-gray-700 font-medium">Audio Language:</span><span className="text-gray-900">{selectedCallRecord.language}</span></div>
              <div className="flex justify-between"><span className="text-gray-700 font-medium">Translation Language:</span><span className="text-gray-900">{selectedCallRecord.translationLanguage}</span></div>
              <div className="flex justify-between"><span className="text-gray-700 font-medium">Sentiment:</span><span className={`inline-block px-3 py-1 rounded-full text-sm font-medium border ${getSentimentColor(selectedCallRecord.sentiment)}`}>{selectedCallRecord.sentiment}</span></div>
              <div className="flex justify-between"><span className="text-gray-700 font-medium">Sarcasm Detected:</span><span className={selectedCallRecord.sarcasm === "Yes" ? "text-orange-700 font-semibold" : "text-green-700 font-semibold"}>{selectedCallRecord.sarcasm}</span></div>
              <div className="flex justify-between"><span className="text-gray-700 font-medium">Status:</span><span className={`inline-block px-3 py-1 rounded-full text-sm font-medium border ${getStatusColor(selectedCallRecord.status)}`}>{selectedCallRecord.status}</span></div>
            </div>
            <button onClick={() => setShowDetailsModal(false)} className="w-full px-4 py-2 bg-violet-500 border border-violet-400 text-white font-semibold rounded-lg hover:bg-violet-600 transition">Close</button>
          </div>
        </div>
      )}

      {/* Audio Player Modal */}
      {showAudioPlayer && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className={`${isDark ? "bg-slate-800 border-slate-700" : "bg-white border-gray-200"} border rounded-lg shadow-lg p-8 max-w-md w-full`}>
            <h3 className={`text-2xl font-bold mb-4 ${isDark ? "text-white" : "text-gray-900"}`}>Call Audio</h3>
            <div className={`mb-4 p-4 ${isDark ? "bg-slate-700" : "bg-gray-100"} rounded-lg`}>
              <p className={`text-sm font-semibold mb-2 ${isDark ? "text-gray-300" : "text-gray-700"}`}>Call ID: {showAudioPlayer.callId || showAudioPlayer.id}</p>
              <p className={`text-sm mb-3 ${isDark ? "text-gray-400" : "text-gray-600"}`}>{showAudioPlayer.timestamp}</p>
              <audio controls className="w-full mb-4" src={`/audio/${showAudioPlayer.fileName}`} />
              <div className={`border-t ${isDark ? "border-slate-600" : "border-gray-300"} pt-3 mt-3`}>
                <p className={`text-xs font-semibold mb-2 ${isDark ? "text-gray-300" : "text-gray-700"}`}>Language: {showAudioPlayer.language}</p>
                <p className={`text-xs ${isDark ? "text-gray-400" : "text-gray-600"}`}>Sentiment: {showAudioPlayer.sentiment} | Sarcasm: {showAudioPlayer.sarcasm}</p>
              </div>
            </div>
            <button onClick={() => setShowAudioPlayer(false)} className={`w-full px-4 py-2 font-semibold rounded-lg transition ${isDark ? "bg-violet-600 text-white hover:bg-violet-700 border border-violet-500" : "bg-violet-500 text-white hover:bg-violet-600 border border-violet-400"}`}>Close</button>
          </div>
        </div>
      )}

      {successMessage && (
        <div className="fixed top-6 right-6 bg-green-500/20 border border-green-400 text-green-700 px-6 py-3 rounded-lg shadow-sm animate-pulse z-40">✓ {successMessage}</div>
      )}
    </div>
  );
}